# Generated by Django 5.2.3 on 2025-07-30 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_reg',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 19, 44, 4, 655055)),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
